
namespace IntegradorIdea.Entidades.ConsultaProcessoResposta
{

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum ServiceAjuizamentoIdType
    {

        /// <remarks/>
        Ajuizamento,
        SolicitaLogon,
        ConfirmaLogon,
        ConsultaProcesso,

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum VersionType
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.0")]
        Item10,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Message : EntidadeBase
    {

        private MessageIdType messageIdField;

        private MessageMessageBody messageBodyField;

        private SignatureType signatureField;

        /// <remarks/>
        public MessageIdType MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        public MessageMessageBody MessageBody
        {
            get
            {
                return this.messageBodyField;
            }
            set
            {
                this.messageBodyField = value;
            }
        }

        public SignatureType Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageIdType
    {

        private ServiceAjuizamentoIdType serviceIdField;

        private VersionType versionField;

        private string msgDescField;

        private string codeField;

        private string fromAddressField;

        private string toAddressField;

        private string dateField;

        /// <remarks/>
        public ServiceAjuizamentoIdType ServiceId
        {
            get
            {
                return this.serviceIdField;
            }
            set
            {
                this.serviceIdField = value;
            }
        }

        /// <remarks/>
        public VersionType Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public string MsgDesc
        {
            get
            {
                return this.msgDescField;
            }
            set
            {
                this.msgDescField = value;
            }
        }

        /// <remarks/>
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string FromAddress
        {
            get
            {
                return this.fromAddressField;
            }
            set
            {
                this.fromAddressField = value;
            }
        }

        /// <remarks/>
        public string ToAddress
        {
            get
            {
                return this.toAddressField;
            }
            set
            {
                this.toAddressField = value;
            }
        }

        /// <remarks/>
        public string Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageMessageBody
    {

        private RespostaType respostaField;

        /// <remarks/>
        public RespostaType Resposta
        {
            get
            {
                return this.respostaField;
            }
            set
            {
                this.respostaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RespostaType
    {

        private MensagemRespostaType mensagemrespostaField;

        /// <remarks/>
        public MensagemRespostaType Mensagem
        {
            get
            {
                return this.mensagemrespostaField;
            }
            set
            {
                this.mensagemrespostaField = value;
            }
        }
        private MessageProcesso mensagemprocessoField;

        /// <remarks/>
        public MessageProcesso Processo
        {
            get
            {
                return this.mensagemprocessoField;
            }
            set
            {
                this.mensagemprocessoField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MensagemRespostaType
    {

        private string codigo;
        private string descricao;

        /// <remarks/>
        public string Codigo
        {
            get
            {
                return this.codigo;
            }
            set
            {
                this.codigo = value;
            }
        }
        /// <remarks/>
        public string Descricao
        {
            get
            {
                return this.descricao;
            }
            set
            {
                this.descricao = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class MessageProcesso
    {

        private string numero;

        private string instancia;

        private string area;

        private ProcessoClasse classe;

        private ProcessoAssuntoPrincipal assuntoprincipal;

        private string segredojustica;

        private string processovirtual;

        private ProcessoForo foro;

        private ProcessoVara vara;

        private string valorcausa;

        private string dataajuizamento;

        private string datadistribuicao;

        private ProcessoTypePartes partes;


        private string[] outrosNumerosField;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Numero
        {
            get
            {
                return this.numero;
            }
            set
            {
                this.numero = value;
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Instancia
        {
            get
            {
                return this.instancia;
            }
            set
            {
                this.instancia = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Area
        {
            get
            {
                return this.area;
            }
            set
            {
                this.area = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessoClasse Classe
        {
            get
            {
                return this.classe;
            }
            set
            {
                this.classe = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessoAssuntoPrincipal AssuntoPrincipal
        {
            get
            {
                return this.assuntoprincipal;
            }
            set
            {
                this.assuntoprincipal = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SegredoJustica
        {
            get
            {
                return this.segredojustica;
            }
            set
            {
                this.segredojustica = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProcessoVirtual
        {
            get
            {
                return this.processovirtual;
            }
            set
            {
                this.processovirtual = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessoVara Vara
        {
            get
            {
                return this.vara;
            }
            set
            {
                this.vara = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessoForo Foro
        {
            get
            {
                return this.foro;
            }
            set
            {
                this.foro = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ValorCausa
        {
            get
            {
                return this.valorcausa;
            }
            set
            {
                this.valorcausa = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataAjuizamento
        {
            get
            {
                return this.dataajuizamento;
            }
            set
            {
                this.dataajuizamento = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DataDistribuicao
        {
            get
            {
                return this.datadistribuicao;
            }
            set
            {
                this.datadistribuicao = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessoTypePartes Partes
        {
            get
            {
                return this.partes;
            }
            set
            {
                this.partes = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OutroNumero", IsNullable = false)]
        public string[] OutrosNumeros
        {
            get
            {
                return this.outrosNumerosField;
            }
            set
            {
                this.outrosNumerosField = value;
            }
        }


        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProcessoClasse
        {

            private string codigo;

            private string descricao;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Codigo
            {
                get
                {
                    return this.codigo;
                }
                set
                {
                    this.codigo = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Descricao
            {
                get
                {
                    return this.descricao;
                }
                set
                {
                    this.descricao = value;
                }
            }
        }
        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProcessoAssuntoPrincipal
        {

            private string codigo;

            private string descricao;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Codigo
            {
                get
                {
                    return this.codigo;
                }
                set
                {
                    this.codigo = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Descricao
            {
                get
                {
                    return this.descricao;
                }
                set
                {
                    this.descricao = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProcessoForo
        {

            private string codigo;

            private string nome;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Codigo
            {
                get
                {
                    return this.codigo;
                }
                set
                {
                    this.codigo = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Nome
            {
                get
                {
                    return this.nome;
                }
                set
                {
                    this.nome = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProcessoVara
        {

            private string codigo;

            private string nome;

            private Competencia competencia;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Codigo
            {
                get
                {
                    return this.codigo;
                }
                set
                {
                    this.codigo = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Nome
            {
                get
                {
                    return this.nome;
                }
                set
                {
                    this.nome = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public Competencia Competencia
            {
                get
                {
                    return this.competencia;
                }
                set
                {
                    this.competencia = value;
                }
            }
        }
        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class Competencia
        {

            private string codigo;

            private string descricao;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Codigo
            {
                get
                {
                    return this.codigo;
                }
                set
                {
                    this.codigo = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Descricao
            {
                get
                {
                    return this.descricao;
                }
                set
                {
                    this.descricao = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProcessoTypePartes
        {

            private ProcessoParte[] partesativas;

            private ProcessoParte[] partespassivas;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Parte", IsNullable = false)]
            public ProcessoParte[] PartesAtivas
            {
                get
                {
                    return this.partesativas;
                }
                set
                {
                    this.partesativas = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Parte", IsNullable = false)]
            public ProcessoParte[] PartesPassivas
            {
                get
                {
                    return this.partespassivas;
                }
                set
                {
                    this.partespassivas = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProcessoParte
        {
            private string seqparte;
            private string nome;
            private string genero;
            private string tipopessoa;
            private string tipoparticipacao;
            private string principal;
            private ParteDocumento[] documentos;
            private ParteAdvogado[] advogados;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string SeqParte
            {
                get
                {
                    return this.seqparte;
                }
                set
                {
                    this.seqparte = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Nome
            {
                get
                {
                    return this.nome;
                }
                set
                {
                    this.nome = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Genero
            {
                get
                {
                    return this.genero;
                }
                set
                {
                    this.genero = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string TipoPessoa
            {
                get
                {
                    return this.tipopessoa;
                }
                set
                {
                    this.tipopessoa = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string TipoParticipacao
            {
                get
                {
                    return this.tipoparticipacao;
                }
                set
                {
                    this.tipoparticipacao = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Principal
            {
                get
                {
                    return this.principal;
                }
                set
                {
                    this.principal = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Documento", IsNullable = false)]
            public ParteDocumento[] Documentos
            {
                get
                {
                    return this.documentos;
                }
                set
                {
                    this.documentos = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Advogado", IsNullable = false)]
            public ParteAdvogado[] Advogados
            {
                get
                {
                    return this.advogados;
                }
                set
                {
                    this.advogados = value;
                }
            }


        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ParteDocumento
        {
            private string tipo;
            private string numero;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Tipo
            {
                get
                {
                    return this.tipo;
                }
                set
                {
                    this.tipo = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Numero
            {
                get
                {
                    return this.numero;
                }
                set
                {
                    this.numero = value;
                }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ParteAdvogado
        {
            private string nome;
            private string oab;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string Nome
            {
                get
                {
                    return this.nome;
                }
                set
                {
                    this.nome = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
            public string OAB
            {
                get
                {
                    return this.oab;
                }
                set
                {
                    this.oab = value;
                }
            }
        }

    }

}
